Collections:
  - Name: PVT
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - RetinaNet
        - PyramidVisionTransformer
        - FPN
    Paper: https://arxiv.org/abs/2102.12122
    README: configs/pvt/README.md
  - Name: PVT-v2
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - RetinaNet
        - PyramidVisionTransformerV2
        - FPN
    Paper: https://arxiv.org/abs/2106.13797
    README: configs/pvt/README.md
Models:
  - Name: retinanet_pvt-t_fpn_1x_coco
    In Collection: PVT
    Config: configs/pvt/retinanet_pvt-t_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 8.5
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.6
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvt-t_fpn_1x_coco/retinanet_pvt-t_fpn_1x_coco_20210831_103110-17b566bd.pth
  - Name: retinanet_pvt-s_fpn_1x_coco
    In Collection: PVT
    Config: configs/pvt/retinanet_pvt-s_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 14.5
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvt-s_fpn_1x_coco/retinanet_pvt-s_fpn_1x_coco_20210906_142921-b6c94a5b.pth
  - Name: retinanet_pvt-m_fpn_1x_coco
    In Collection: PVT
    Config: configs/pvt/retinanet_pvt-m_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 20.9
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.7
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvt-m_fpn_1x_coco/retinanet_pvt-m_fpn_1x_coco_20210831_103243-55effa1b.pth
  - Name: retinanet_pvtv2-b0_fpn_1x_coco
    In Collection: PVT-v2
    Config: configs/pvt/retinanet_pvtv2-b0_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 7.4
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.1
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b0_fpn_1x_coco/retinanet_pvtv2-b0_fpn_1x_coco_20210831_103157-13e9aabe.pth
  - Name: retinanet_pvtv2-b1_fpn_1x_coco
    In Collection: PVT-v2
    Config: configs/pvt/retinanet_pvtv2-b1_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 9.5
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.2
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b1_fpn_1x_coco/retinanet_pvtv2-b1_fpn_1x_coco_20210831_103318-7e169a7d.pth
  - Name: retinanet_pvtv2-b2_fpn_1x_coco
    In Collection: PVT-v2
    Config: configs/pvt/retinanet_pvtv2-b2_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 16.2
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.6
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b2_fpn_1x_coco/retinanet_pvtv2-b2_fpn_1x_coco_20210901_174843-529f0b9a.pth
  - Name: retinanet_pvtv2-b3_fpn_1x_coco
    In Collection: PVT-v2
    Config: configs/pvt/retinanet_pvtv2-b3_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 23.0
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 46.0
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b3_fpn_1x_coco/retinanet_pvtv2-b3_fpn_1x_coco_20210903_151512-8357deff.pth
  - Name: retinanet_pvtv2-b4_fpn_1x_coco
    In Collection: PVT-v2
    Config: configs/pvt/retinanet_pvtv2-b4_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 17.0
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 46.3
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b4_fpn_1x_coco/retinanet_pvtv2-b4_fpn_1x_coco_20210901_170151-83795c86.pth
  - Name: retinanet_pvtv2-b5_fpn_1x_coco
    In Collection: PVT-v2
    Config: configs/pvt/retinanet_pvtv2-b5_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 18.7
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 46.1
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b5_fpn_1x_coco/retinanet_pvtv2-b5_fpn_1x_coco_20210902_201800-3420eb57.pth
